### ISSUE TITLE
Some combination of authored styles causing "cover" image to disappear

### ISSUE THREAD

**Issue by danielweck** [readium/readium-css#103]
This happens in both scroll and paginated modes in Thorium. I am filing in ReadiumCSS to see if this affects other reading systems.

EPUB contains `HachetteEpubV1.3.css` with:

```css
.sectionpp {
    left: 0;
    top: 0;
    height: 100%;
    width: 100%;
    overflow: hidden;
    text-align: center;
    position: absolute;
}
```

and XHTML markup:

```xml
<section xmlns="http://www.w3.org/1999/xhtml" class="sectionpp" xmlns:epub="http://www.idpf.org/2007/ops" epub:type="cover" role="doc-cover"><a id="cover" tabindex="-1"><img alt="" class="imgpp" src="cover/cover.jpg" /></a>
</section>
```

If I remove `position: absolute;`, or `height: 100%;`, the image is displayed normally. Otherwise, invisible (the image CSS box itself is fine, it is the containing div that causes issues)

<img width="1454" alt="Screenshot 2021-03-22 at 15 26 32" src="https://user-images.githubusercontent.com/625201/112014959-486ab100-8b23-11eb-9a8a-fbf9e9b3b7f1.png">
