### ISSUE TITLE
EPUB with `overflow-x: hidden` style breaks pagination

### ISSUE THREAD

**Issue by mickael-menu** [readium/readium-css#119]
> This epub has `overflow-x: hidden` CSS for the `<body>` tag. That is what is causing this.  @mickael-menu should Readium CSS be changed to always override that?

_Originally posted by @stevenzeck in https://github.com/readium/kotlin-toolkit/issues/292#issuecomment-1301535645_

---

### What happened?
The attached epub's chapter shows in a single page, where it should show over several pages.

https://user-images.githubusercontent.com/38096011/199537331-a167f47a-0f17-4765-8b07-a173600f3432.mp4

### Expected behavior

Only a part of the chapter should show, and the rest of the chapter should be displayed after navigating to the next page.

### Actual behavior
The chapter is rendered in a single page.

### How to reproduce?

[‎⁨الحرب_والسلم_(الكتاب_الأول)⁩.epub.zip](https://github.com/readium/kotlin-toolkit/files/9920387/_._._.epub.zip)
The ebup download url: https://downloads.hindawi.org/books/26307461.epub

### Environment

* Readium version: 2.2.1

#### Development environment

* OS: macOS Ventura 13.0
* IDE: Android Studio Dolphin | 2021.3.1 Patch 1

#### Testing device

* Android version: 11
* Model: Realme Narzo 50i
* Is it an emulator? No

### Additional context

* Are you willing to fix the problem and contribute a pull request? Yes, Please

**Comment by danielweck** [comment]
I tested `الحرب_والسلم_(الكتاب_الأول).epub` with Thorium. The page renders fine, I think:

<img width="1552" alt="Screenshot 2022-11-03 at 16 05 58" src="https://user-images.githubusercontent.com/625201/199772993-33932280-0912-4e3f-b1b4-314fa005c686.png">

...but, Thorium injects additional stylesheets immediately after the ReadiumCSS "after" layer (which itself comes after publishers styles, which itself comes after ReadiumCSS "before" layer).
The injected CSS is the product of incremental findings following weird edge-case bug reports (there is still a known problem with some HTML pages that don't extend the full height, so it is not "perfect" yet). The CSS bugs are super tricky to reproduce, sometimes impossible from the Web Inspector (must author the CSS at source and do a hard page reload, can't dynamically change properties in the style debugger).

For what it's worth, here is the current stack of CSS overrides in Thorium:

```css
<style xmlns="http://www.w3.org/1999/xhtml" id="Readium2-electron-visibility-mask" type="text/css">

/*
https://github.com/readium/readium-css/issues/117
no new stacking context, otherwise massive performance degradation with CSS Columns in large HTML documents
(web inspector profiler shows long paint times, some layout recalc triggers too)
*/
:root {
    -webkit-perspective: none !important;
    perspective: none !important;
}

:root[style].r2-css-paginated:not(.r2-fixed-layout),
:root.r2-css-paginated:not(.r2-fixed-layout) {
    overflow: visible !important;
}
:root[style].r2-css-paginated:not(.r2-fixed-layout) &gt; body,
:root.r2-css-paginated:not(.r2-fixed-layout) &gt; body {
    overflow-x: hidden !important;
    overflow-y: visible !important;
}

:root[style].r2-fixed-layout,
:root.r2-fixed-layout {
    overflow: hidden !important;
}
:root[style].r2-fixed-layout &gt; body,
:root.r2-fixed-layout &gt; body {
    overflow: hidden !important;
    margin: 0 !important;
}

:root.r2-css-paginated &gt; body,
:root:not(.r2-css-paginated) &gt; body,
:root.r2-fixed-layout &gt; body,
:root:not(.r2-fixed-layout) &gt; body,
:root[style].r2-css-paginated &gt; body,
:root[style]:not(.r2-css-paginated) &gt; body,
:root[style].r2-fixed-layout &gt; body,
:root[style]:not(.r2-fixed-layout) &gt; body {
    position: relative !important;
}

:root[style]:not(.r2-css-paginated):not(.r2-fixed-layout),
:root:not(.r2-css-paginated):not(.r2-fixed-layout) {
    height: 100vh !important;
}

:root[style].r2-css-paginated:not(.r2-fixed-layout),
:root.r2-css-paginated:not(.r2-fixed-layout) {
    /* display: block; */
    /*
    Chrome Electron 19 - Chrome v102 CSS regression bug!
    display: flex; ... then transition to block or flow-root
    See SKIP_LINK_ID rules below :(
    (hacky, but works without regressions or layout shift)
    */
}
:root[style]:not(.r2-fixed-layout) &gt; body,
:root:not(.r2-fixed-layout) &gt; body {
    min-height: inherit;
}
:root[style]:not(.r2-css-paginated):not(.r2-fixed-layout) &gt; body,
:root:not(.r2-css-paginated):not(.r2-fixed-layout) &gt; body {
    height: inherit;
}

</style>
```

**Comment by danielweck** [comment]
Ah, I disabled the CSS hacks (see stylesheet snippet above), and the Arabic RTL still text flows correctly in Thorium. I guess the Chromium web browser engine is happier in Thorium than in Android? :)

**Comment by mickael-menu** [comment]
Thanks for the feedback @danielweck. I tested on iOS and it worked fine as well, so it might be an Android-specific issue.

Interestingly the edge taps work on Android, it's only the swipes that fail. Might be an issue in the gesture recognition.

**Comment by danielweck** [comment]
What the hell?! Thorium is broken with latest Electron build (updated Chromium). Same pagination problem with overflow X

**Comment by mickael-menu** [comment]
😅 This is what I injected to fix the issue, inspired by your snippets:

```css
:root[style], :root { overflow: visible !important; }
:root[style] > body, :root > body { overflow: visible !important; }
```
