### ISSUE TITLE
Font issue on android with large fonts on high DPI devices

### ISSUE THREAD

**Issue by ne0rrmatrix** [readium/readium-css#176]
When using readium css in  a Dotnet Maui WebView app with an Epub html chapter in an `iframe` I have had issue with setting large font sizes. This is most likely developer error(My error) not yours. Your Readium CSS  is an absolute wonder and pretty much just works very well. 

But I wanted to add support for letting users adjust font size and on android I have run into a brick wall. I have spent about 2 months on this one issue. When I select a font size, say 200% and set the readium user variable it does increase the font. But when I change pages it suddenly  has visible margins or something is messing with page display. I have set zero margins and padding. I have set the absolute min settings to have the CSS package work. 

I have tried both my ebook collection and for testing purposes switched to using the samples in repo here. The underlying issue is every page turn the text is displayed slight right of previous page. This only happens when setting font size above a specific percentage. At normal size everything works 100 percent perfect. The windows app  works 100 percent and I have zero issues with it. For windows it has been ready for testing for months. No my  app still needs a significant amount of work as I want to eventually be standards compliant. May take years but I will work towards this goal. 

index:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Test</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="EpubText.css">
</head>
<body>
    <iframe title="Book" src="about:blank" class="page" id="page"></iframe>
    <script src="EpubText.js"></script>
</body>
</html>
```
index css:

```css
html, body {
    margin: 0;
    padding: 0;
    background-color: var(--background-color);
}

:root {
    --background-color: transparent;
}

body {
    height: 100vh;
    width: 100vw;
}

iframe {
    border: 0;
    width: 100%; // have tried 100vw and tried setting min and max width and height.
    height: 100vh;
    padding: 0 !important;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-color: transparent;
}
```
page turning javascript: 
```javascript
 const scrollLeft = () => {
     const gap = parseInt(window.getComputedStyle(frame.contentWindow.document.documentElement).getPropertyValue("column-gap"));
     frame.contentWindow.scrollTo(frame.contentWindow.scrollX - frame.contentWindow.innerWidth - gap, 0);
 };


 const scrollRight = () => {
     const gap = parseInt(window.getComputedStyle(frame.contentWindow.document.documentElement).getPropertyValue("column-gap"));
     frame.contentWindow.scrollTo(frame.contentWindow.scrollX + frame.contentWindow.innerWidth + gap, 0);
 };
```
I have spent more than two months trying every possible variation i could think of to get this to work. I have tried embedding the android font patch. It is currently embedded and fixes a few issues. I will also say this issue does not occur in any browser when using fonts of different sizes. This is an issue only with android on select devices. Any high dpi android tablet will have issues.
