### ISSUE TITLE
Should the `overflow: clip` fix be an opt-in?

### ISSUE THREAD

**Issue by mickael-menu** [readium/readium-css#183]
I'm trying to integrate Readium CSS v2 in the Swift toolkit, but faced an issue caused by this piece of code: https://github.com/readium/css/commit/623dca9026e507161aa91876ca131a4ba262b817

```css
@supports (overflow: clip) {
  :root {
     overflow: clip;
  }

  body {
     overflow: clip;
     overflow-clip-margin: content-box;
  }
}
```

This prevents the web view from scrolling the content "naturally" when in paginated mode. I think it's not an issue with the Web Reader because the content is translated manually instead of relying on the iframe's scroll.

I applied a workaround taken from the Kotlin toolkit for a different issue, which reverses the overflow. But having this as an opt-in/out in Readium CSS would be helpful.

```css
// Fix broken pagination when a book contains `overflow-x: hidden`.
// https://github.com/readium/kotlin-toolkit/issues/292
// Inspired by https://github.com/readium/readium-css/issues/119#issuecomment-1302348238
inj.append(.style(
    """
    :root[style], :root { overflow: visible !important; }
    :root[style] > body, :root > body { overflow: visible !important; }
    """
))
```
