### ISSUE TITLE
Namespace Selection

### ISSUE THREAD

**Issue by tooolbox** [readium/readium-css#82]
I'm submitting a question.

**Short description of the issue/suggestion:**

I would like to know if there's a standard/blessed way in Readium CSS to select elements with a namespaced attribute.

In [ReadiumCSS-night_mode.css](https://github.com/readium/readium-css/blob/master/css/src/modules/ReadiumCSS-night_mode.css#L48) I see this:
```css
:root:--night-mode *[epub\:type~="titlepage"] img:only-child {
  -webkit-filter: invert(100%);
  filter: invert(100%);
}
```

But in [ReadiumCSS-base](https://github.com/readium/readium-css/blob/master/css/src/modules/ReadiumCSS-base.css#L8) I see namespace declarations, which [are supposed to enable](https://oreillymedia.github.io/Using_SVG/extras/ch03-namespaces.html) `[ns|attr="value"]` syntax:
```css
@namespace url("http://www.w3.org/1999/xhtml");
@namespace epub url("http://www.idpf.org/2007/ops");
@namespace m url("http://www.w3.org/1998/Math/MathML/");
@namespace svg url("http://www.w3.org/2000/svg");
```

So...  `|` or `\:` ?  (I am targeting something in the `epub` namespace, so it's declared, in case that's a question.)
